import random
from kanji import Kanji
from pontuacao import Pontuacao

class Quiz:
    def __init__(self):
        self.perguntas = []
        self.indice_atual = 0
        self.pontuacao = Pontuacao()

    def carregar_perguntas(self, nivel_dificuldade, quantidade):
        banco_de_kanji = [
            # 小学1年
            
            Kanji("一", ["ichi"], "1年"),
            Kanji("二", ["ni"], "1年"),
            Kanji("三", ["san"], "1年"),
            Kanji("四", ["shi", "yon"], "1年"),
            Kanji("五", ["go"], "1年"),
            Kanji("六", ["roku"], "1年"),
            Kanji("七", ["shichi", "nana"], "1年"),
            Kanji("八", ["hachi"], "1年"),
            Kanji("九", ["kyuu", "ku"], "1年"),
            Kanji("十", ["juu", "tô"], "1年"),
            Kanji("百", ["hyaku"], "1年"),
            Kanji("千", ["sen"], "1年"),
            Kanji("上", ["ue", "jou"], "1年"),
            Kanji("下", ["shita", "ka"], "1年"),
            Kanji("左", ["hidari"], "1年"),
            Kanji("右", ["migi"], "1年"),
            Kanji("中", ["naka", "chuu"], "1年"),
            Kanji("大", ["oo", "dai"], "1年"),
            Kanji("小", ["chii(sai)", "chii", "shou"], "1年"),
            Kanji("月", ["tsuki", "getsu"], "1年"),
            Kanji("日", ["hi", "bi", "nichi"], "1年"),
            Kanji("年", ["toshi", "nen"], "1年"),
            Kanji("早", ["haya", "sou"], "1年"),
            Kanji("木", ["ki", "moku"], "1年"),
            Kanji("林", ["hayashi", "rin"], "1年"),
            Kanji("山", ["yama", "san"], "1年"),
            Kanji("川", ["kawa", "sen"], "1年"),
            Kanji("土", ["tsuchi", "do"], "1年"),
            Kanji("空", ["sora", "kuu"], "1年"),
            Kanji("田", ["ta", "den"], "1年"),
            Kanji("天", ["ten", "ama"], "1年"),
            Kanji("生", ["ikiru", "sei"], "1年"),
            Kanji("花", ["hana"], "1年"),
            Kanji("草", ["kusa"], "1年"),
            Kanji("虫", ["mushi"], "1年"),
            Kanji("犬", ["inu", "ken"], "1年"),
            Kanji("人", ["hito", "jin"], "1年"),
            Kanji("名", ["na", "mei"], "1年"),
            Kanji("女", ["onna", "jo"], "1年"),
            Kanji("男", ["otoko", "dan"], "1年"),
            Kanji("子", ["ko", "shi"], "1年"),
            Kanji("目", ["me", "moku"], "1年"),
            Kanji("耳", ["mimi"], "1年"),
            Kanji("口", ["kuchi", "kou"], "1年"),
            Kanji("手", ["te", "shu"], "1年"),
            Kanji("足", ["ashi", "soku"], "1年"),
            Kanji("見", ["miru", "ken"], "1年"),
            Kanji("音", ["oto", "on", "ne"], "1年"),
            Kanji("力", ["chikara", "ryoku", "riki"], "1年"),
            Kanji("気", ["ki"], "1年"),
            Kanji("円", ["en"], "1年"),
            Kanji("入", ["hairu", "nyuu"], "1年"),
            Kanji("出", ["deru", "shutsu"], "1年"),
            Kanji("立", ["tatsu", "ritsu"], "1年"),
            Kanji("休", ["yasumu", "kyuu"], "1年"),
            Kanji("先", ["saki", "sen"], "1年"),
            Kanji("夕", ["yuu"], "1年"),
            Kanji("本", ["hon", "moto"], "1年"),
            Kanji("文", ["bun", "fumi"], "1年"),
            Kanji("字", ["ji"], "1年"),
            Kanji("学", ["manabu", "gaku"], "1年"),
            Kanji("校", ["kou"], "1年"),
            Kanji("村", ["mura", "son"], "1年"),
            Kanji("町", ["machi", "chou"], "1年"),
            Kanji("森", ["mori", "shin"], "1年"),
            Kanji("正", ["tadashii", "sei"], "1年"),
            Kanji("水", ["mizu", "sui"], "1年"),
            Kanji("火", ["hi", "ka"], "1年"),
            Kanji("玉", ["tama", "gyoku"], "1年"),
            Kanji("王", ["ou"], "1年"),
            Kanji("石", ["ishi", "seki"], "1年"),
            Kanji("竹", ["take", "chiku"], "1年"),
            Kanji("糸", ["ito", "shi"], "1年"),
            Kanji("貝", ["kai"], "1年"),
            Kanji("車", ["kuruma", "sha"], "1年"),
            Kanji("金", ["kane", "kin"], "1年"),
            Kanji("雨", ["ame", "u"], "1年"),
            Kanji("赤", ["aka", "seki"], "1年"),
            Kanji("青", ["ao", "sei"], "1年"),
            Kanji("白", ["shiro", "haku"], "1年"),

            # 小学2年
            Kanji("数", ["suu", "kazu"], "2年"),
            Kanji("多", ["ta", "oo"], "2年"),
            Kanji("少", ["shou", "sukoshi"], "2年"),
            Kanji("万", ["man", "ban"], "2年"),
            Kanji("半", ["han"], "2年"),
            Kanji("形", ["kei", "katachi"], "2年"),
            Kanji("太", ["tai", "futo"], "2年"),
            Kanji("細", ["sai", "hoso"], "2年"),
            Kanji("広", ["kou", "hiro"], "2年"),
            Kanji("長", ["chou", "naga"], "2年"),
            Kanji("点", ["ten"], "2年"),
            Kanji("丸", ["maru"], "2年"),
            Kanji("交", ["kou", "maji"], "2年"),
            Kanji("光", ["kou", "hikari"], "2年"),
            Kanji("角", ["kaku", "kado"], "2年"),
            Kanji("計", ["kei", "hakaru"], "2年"),
            Kanji("直", ["choku", "nao"], "2年"),
            Kanji("線", ["sen"], "2年"),
            Kanji("矢", ["ya"], "2年"),
            Kanji("弱", ["jaku", "yowa"], "2年"),
            Kanji("強", ["kyou", "tsuyo"], "2年"),
            Kanji("高", ["kou", "taka"], "2年"),
            Kanji("同", ["dou"], "2年"),
            Kanji("親", ["oya", "shin"], "2年"),
            Kanji("母", ["haha", "bo"], "2年"),
            Kanji("父", ["chichi", "fu"], "2年"),
            Kanji("姉", ["ane", "shi"], "2年"),
            Kanji("兄", ["ani", "kei"], "2年"),
            Kanji("弟", ["otouto", "tei"], "2年"),
            Kanji("妹", ["imouto", "mai"], "2年"),
            Kanji("自", ["ji"], "2年"),
            Kanji("友", ["yuu", "tomo"], "2年"),
            Kanji("体", ["tai", "karada"], "2年"),
            Kanji("毛", ["ke"], "2年"),
            Kanji("頭", ["atama", "tou"], "2年"),
            Kanji("顔", ["kao", "gan"], "2年"),
            Kanji("首", ["kubi"], "2年"),
            Kanji("心", ["kokoro", "shin"], "2年"),
            Kanji("時", ["ji", "toki"], "2年"),
            Kanji("曜", ["you"], "2年"),
            Kanji("朝", ["asa"], "2年"),
            Kanji("昼", ["hiru"], "2年"),
            Kanji("夜", ["yoru", "ya"], "2年"),
            Kanji("分", ["fun", "bun", "wa(keru)", "wa"], "2年"),
            Kanji("週", ["shuu"], "2年"),
            Kanji("春", ["haru"], "2年"),
            Kanji("夏", ["natsu"], "2年"),
            Kanji("秋", ["aki"], "2年"),
            Kanji("冬", ["fuyu"], "2年"),
            Kanji("今", ["ima", "kon"], "2年"),
            Kanji("新", ["atarashii", "shin"], "2年"),
            Kanji("古", ["furui", "ko"], "2年"),
            Kanji("間", ["aida", "kan"], "2年"),
            Kanji("方", ["hou", "kata"], "2年"),
            Kanji("北", ["kita", "hoku"], "2年"),
            Kanji("南", ["minami", "nan"], "2年"),
            Kanji("東", ["higashi", "tou"], "2年"),
            Kanji("西", ["nishi", "sei"], "2年"),
            Kanji("遠", ["too(i)", "too", "tô", "en"], "2年"),
            Kanji("近", ["chikai", "kin"], "2年"),
            Kanji("前", ["mae", "zen"], "2年"),
            Kanji("後", ["ato", "go"], "2年"),
            Kanji("内", ["uchi", "nai"], "2年"),
            Kanji("外", ["soto", "gai"], "2年"),
            Kanji("場", ["ba", "jou"], "2年"),
            Kanji("地", ["chi", "ji"], "2年"),
            Kanji("国", ["kuni", "koku"], "2年"),
            Kanji("園", ["sono", "en"], "2年"),
            Kanji("谷", ["tani", "koku"], "2年"),
            Kanji("野", ["no", "ya"], "2年"),
            Kanji("原", ["hara", "gen"], "2年"),
            Kanji("里", ["sato", "ri"], "2年"),
            Kanji("市", ["shi", "ichi"], "2年"),
            Kanji("京", ["kyou", "kei"], "2年"),
            Kanji("風", ["kaze", "fuu"], "2年"),
            Kanji("雪", ["yuki"], "2年"),
            Kanji("雲", ["kumo"], "2年"),
            Kanji("池", ["ike"], "2年"),
            Kanji("海", ["umi", "kai"], "2年"),
            Kanji("岩", ["iwa", "gan"], "2年"),
            Kanji("星", ["hoshi", "sei"], "2年"),
            Kanji("室", ["muro", "shitsu"], "2年"),
            Kanji("戸", ["to", "ko"], "2年"),
            Kanji("家", ["ie", "ka"], "2年"),
            Kanji("寺", ["tera", "ji"], "2年"),
            Kanji("通", ["too(ru)", "too", "tô", "tsuu"], "2年"),
            Kanji("門", ["mon"], "2年"),
            Kanji("道", ["michi", "dou"], "2年"),
            Kanji("話", ["hanashi", "wa"], "2年"),
            Kanji("言", ["iu", "gen"], "2年"),
            Kanji("答", ["kotaeru", "tou"], "2年"),
            Kanji("声", ["koe", "sei"], "2年"),
            Kanji("聞", ["ki(ku)", "ki", "bun"], "2年"),
            Kanji("語", ["go", "kata(ru)", "kata"], "2年"),
            Kanji("読", ["yomu", "doku"], "2年"),
            Kanji("書", ["kaku", "sho"], "2年"),
            Kanji("記", ["ki"], "2年"),
            Kanji("紙", ["kami", "shi"], "2年"),
            Kanji("画", ["ga", "kaku"], "2年"),
            Kanji("絵", ["e"], "2年"),
            Kanji("図", ["zu", "to"], "2年"),
            Kanji("工", ["kou", "ku"], "2年"),
            Kanji("教", ["oshieru", "kyou"], "2年"),
            Kanji("晴", ["hare", "sei"], "2年"),
            Kanji("思", ["omo(u)", "omo", "shi"], "2年"),
            Kanji("考", ["kangaeru", "kou"], "2年"),
            Kanji("知", ["shiru", "chi"], "2年"),
            Kanji("才", ["sai"], "2年"),
            Kanji("理", ["ri"], "2年"),
            Kanji("算", ["san"], "2年"),
            Kanji("作", ["tsukuru", "saku"], "2年"),
            Kanji("元", ["moto", "gen"], "2年"),
            Kanji("食", ["taberu", "shoku"], "2年"),
            Kanji("肉", ["niku"], "2年"),
            Kanji("馬", ["uma", "ba"], "2年"),
            Kanji("牛", ["ushi", "gyuu"], "2年"),
            Kanji("魚", ["sakana", "gyo"], "2年"),
            Kanji("鳥", ["tori", "chou"], "2年"),
            Kanji("羽", ["hane", "u"], "2年"),
            Kanji("鳴", ["naku", "mei"], "2年"),
            Kanji("麦", ["mugi", "baku"], "2年"),
            Kanji("米", ["kome", "bei"], "2年"),
            Kanji("茶", ["cha"], "2年"),
            Kanji("色", ["iro", "shoku"], "2年"),
            Kanji("黄", ["ki", "ou"], "2年"),
            Kanji("黒", ["kuro", "koku"], "2年"),
            Kanji("来", ["kuru", "rai"], "2年"),
            Kanji("行", ["i(ku)", "i", "kou"], "2年"),
            Kanji("帰", ["kaeru", "ki"], "2年"),
            Kanji("歩", ["aruku", "ho"], "2年"),
            Kanji("走", ["hashiru", "sou"], "2年"),
            Kanji("止", ["to(meru)", "to", "shi"], "2年"),
            Kanji("活", ["katsu"], "2年"),
            Kanji("店", ["mise", "ten"], "2年"),
            Kanji("買", ["ka(u)", "ka", "bai"], "2年"),
            Kanji("売", ["uru", "bai"], "2年"),
            Kanji("午", ["go"], "2年"),
            Kanji("汽", ["ki"], "2年"),
            Kanji("弓", ["yumi", "kyuu"], "2年"),
            Kanji("回", ["mawaru", "kai"], "2年"),
            Kanji("会", ["a(u)", "a", "kai"], "2年"),
            Kanji("組", ["kumi", "so"], "2年"),
            Kanji("船", ["fune", "sen"], "2年"),
            Kanji("明", ["mei", "aka(rui)", "aka"], "2年"),
            Kanji("社", ["sha", "yashiro"], "2年"),
            Kanji("切", ["kiru", "setsu"], "2年"),
            Kanji("電", ["den"], "2年"),
            Kanji("毎", ["mai"], "2年"),
            Kanji("合", ["au", "gou"], "2年"),
            Kanji("当", ["tou", "ataru"], "2年"),
            Kanji("台", ["dai", "tai"], "2年"),
            Kanji("楽", ["raku", "gaku"], "2年"),
            Kanji("公", ["kou"], "2年"),
            Kanji("引", ["hi(ku)", "hi", "in"], "2年"),
            Kanji("科", ["ka"], "2年"),
            Kanji("歌", ["uta", "ka"], "2年"),
            Kanji("刀", ["katana", "tou"], "2年"),
            Kanji("番", ["ban"], "2年"),
            Kanji("用", ["you"], "2年"),
            Kanji("何", ["nani", "ka"], "2年"),

            # 小学3年
            Kanji("丁", ["chou"], "3年"),
            Kanji("世", ["yo", "sei"], "3年"),
            Kanji("両", ["ryou"], "3年"),
            Kanji("主", ["shu", "nushi"], "3年"),
            Kanji("乗", ["jou", "noru"], "3年"),
            Kanji("予", ["yo"], "3年"),
            Kanji("事", ["ji", "koto"], "3年"),
            Kanji("仕", ["shi", "tsuka"], "3年"),
            Kanji("他", ["ta", "hoka"], "3年"),
            Kanji("代", ["dai", "yo"], "3年"),
            Kanji("住", ["juu", "sumu"], "3年"),
            Kanji("使", ["shi", "tsuka"], "3年"),
            Kanji("係", ["kakari", "gakari"], "3年"),
            Kanji("倍", ["bai"], "3年"),
            Kanji("全", ["zen", "subete"], "3年"),
            Kanji("具", ["gu"], "3年"),
            Kanji("写", ["sha", "utsusu"], "3年"),
            Kanji("列", ["retsu"], "3年"),
            Kanji("助", ["jo", "tasu(keru)", "tasu", "suke"], "3年"),
            Kanji("勉", ["ben"], "3年"),
            Kanji("動", ["dou", "ugo(ku)", "ugo"], "3年"),
            Kanji("勝", ["shou", "katsu"], "3年"),
            Kanji("化", ["ka", "ba(keru)", "ba"], "3年"),
            Kanji("区", ["ku"], "3年"),
            Kanji("医", ["i"], "3年"),
            Kanji("去", ["kyo", "saru"], "3年"),
            Kanji("反", ["han", "tan"], "3年"),
            Kanji("取", ["toru"], "3年"),
            Kanji("受", ["ju", "u(keru)", "u"], "3年"),
            Kanji("号", ["gou"], "3年"),
            Kanji("向", ["muku", "kou"], "3年"),
            Kanji("君", ["kimi", "kun"], "3年"),
            Kanji("味", ["aji", "mi"], "3年"),
            Kanji("命", ["inochi", "mei"], "3年"),
            Kanji("和", ["wa", "yawa(rai)", "yawa"], "3年"),
            Kanji("品", ["hin", "shina"], "3年"),
            Kanji("員", ["in"], "3年"),
            Kanji("商", ["shou", "akinai"], "3年"),
            Kanji("問", ["mon", "to(u)", "to"], "3年"),
            Kanji("坂", ["saka"], "3年"),
            Kanji("央", ["ou"], "3年"),
            Kanji("始", ["haji(meru)", "haji", "shi"], "3年"),
            Kanji("委", ["i", "yuda(neru)"], "3年"),
            Kanji("守", ["mamoru", "shu"], "3年"),
            Kanji("安", ["yasu(i)", "yasu", "an"], "3年"),
            Kanji("定", ["tei", "sada(maru)", "sada"], "3年"),
            Kanji("実", ["mi", "jitsu"], "3年"),
            Kanji("客", ["kyaku", "kyaku"], "3年"),
            Kanji("宮", ["miya", "kyuu"], "3年"),
            Kanji("宿", ["yado", "shuku"], "3年"),
            Kanji("寒", ["samui", "kan"], "3年"),
            Kanji("対", ["tai", "tsui"], "3年"),
            Kanji("局", ["kyoku"], "3年"),
            Kanji("屋", ["ya", "oku"], "3年"),
            Kanji("岸", ["kishi", "gan"], "3年"),
            Kanji("島", ["shima", "tou"], "3年"),
            Kanji("州", ["shuu"], "3年"),
            Kanji("帳", ["chou"], "3年"),
            Kanji("平", ["hira", "hei"], "3年"),
            Kanji("幸", ["sachi", "kou"], "3年"),
            Kanji("度", ["do", "tabi"], "3年"),
            Kanji("庫", ["ko", "kura"], "3年"),
            Kanji("庭", ["niwa"], "3年"),
            Kanji("式", ["shiki"], "3年"),
            Kanji("役", ["yaku", "eki"], "3年"),
            Kanji("待", ["matsu", "tai"], "3年"),
            Kanji("急", ["kyuu", "isogu"], "3年"),
            Kanji("息", ["iki", "soku"], "3年"),
            Kanji("悪", ["aku", "waru(i)", "waru"], "3年"),
            Kanji("悲", ["kana(shii)", "kana", "hi"], "3年"),
            Kanji("想", ["sou", "omo(u)", "omo"], "3年"),
            Kanji("意", ["i"], "3年"),
            Kanji("感", ["kan"], "3年"),
            Kanji("所", ["tokoro", "sho"], "3年"),
            Kanji("打", ["da", "utsu"], "3年"),
            Kanji("投", ["tou", "na(geru)", "na"], "3年"),
            Kanji("拾", ["shuu", "hiro(u)", "hiro"], "3年"),
            Kanji("持", ["mochi", "ji"], "3年"),
            Kanji("指", ["yubi", "shi"], "3年"),
            Kanji("放", ["hanasu", "hou"], "3年"),
            Kanji("整", ["sei", "totono(u)", "totono"], "3年"),
            Kanji("旅", ["tabi", "ryo"], "3年"),
            Kanji("族", ["zoku"], "3年"),
            Kanji("昔", ["mukashi"], "3年"),
            Kanji("昭", ["shou"], "3年"),
            Kanji("暑", ["atsu(i)", "atsu", "sho"], "3年"),
            Kanji("暗", ["kura(i)", "kura", "an"], "3年"),
            Kanji("曲", ["kyoku", "magaru"], "3年"),
            Kanji("有", ["aru", "yuu"], "3年"),
            Kanji("服", ["fuku"], "3年"),
            Kanji("期", ["ki"], "3年"),
            Kanji("板", ["ita"], "3年"),
            Kanji("柱", ["hashira"], "3年"),
            Kanji("根", ["ne", "kon"], "3年"),
            Kanji("植", ["shoku", "u(eru)", "u"], "3年"),
            Kanji("業", ["gyou"], "3年"),
            Kanji("様", ["you", "sama"], "3年"),
            Kanji("横", ["yoko", "ou"], "3年"),
            Kanji("橋", ["hashi", "kyou"], "3年"),
            Kanji("次", ["tsugi", "ji"], "3年"),
            Kanji("歯", ["ha"], "3年"),
            Kanji("死", ["shi"], "3年"),
            Kanji("氷", ["kori", "hyou"], "3年"),
            Kanji("決", ["ketsu", "ki(meru)", "ki"], "3年"),
            Kanji("油", ["abura"], "3年"),
            Kanji("波", ["nami"], "3年"),
            Kanji("注", ["chu", "soso(gu)", "soso"], "3年"),
            Kanji("泳", ["oyo(gu)", "oyo", "ei"], "3年"),
            Kanji("洋", ["you"], "3年"),
            Kanji("流", ["nagare", "ryuu"], "3年"),
            Kanji("消", ["kesu", "shou"], "3年"),
            Kanji("深", ["fukai", "shin"], "3年"),
            Kanji("温", ["atata(kai)", "on", "atata"], "3年"),
            Kanji("港", ["minato", "kou"], "3年"),
            Kanji("湖", ["mizuumi", "ko"], "3年"),
            Kanji("湯", ["yu", "tou"], "3年"),
            Kanji("漢", ["kan"], "3年"),
            Kanji("炭", ["sumi", "tan"], "3年"),
            Kanji("物", ["mono", "butsu"], "3年"),
            Kanji("球", ["kyuu"], "3年"),
            Kanji("由", ["yuu", "yoshi"], "3年"),
            Kanji("申", ["mou(su)", "shin", "mou"], "3年"),
            Kanji("界", ["kai"], "3年"),
            Kanji("畑", ["hatake"], "3年"),
            Kanji("病", ["byou", "yamai"], "3年"),
            Kanji("発", ["hatsu"], "3年"),
            Kanji("登", ["noboru", "tou"], "3年"),
            Kanji("皮", ["kawa", "hi"], "3年"),
            Kanji("皿", ["sara"], "3年"),
            Kanji("相", ["ai", "sou"], "3年"),
            Kanji("県", ["ken"], "3年"),
            Kanji("真", ["ma", "shin"], "3年"),
            Kanji("着", ["chaku", "ki(ru)", "ki"], "3年"),
            Kanji("短", ["mijikai", "tan"], "3年"),
            Kanji("研", ["ken"], "3年"),
            Kanji("礼", ["rei"], "3年"),
            Kanji("神", ["kami", "shin"], "3年"),
            Kanji("祭", ["matsuri", "sai"], "3年"),
            Kanji("福", ["fuku"], "3年"),
            Kanji("秒", ["byou"], "3年"),
            Kanji("究", ["kyuu"], "3年"),
            Kanji("章", ["shou"], "3年"),
            Kanji("童", ["dou"], "3年"),
            Kanji("笛", ["fue", "teki"], "3年"),
            Kanji("第", ["dai"], "3年"),
            Kanji("筆", ["fude", "hitsu"], "3年"),
            Kanji("等", ["tou"], "3年"),
            Kanji("箱", ["hako"], "3年"),
            Kanji("級", ["kyuu"], "3年"),
            Kanji("終", ["o", "o(waru)", "shu", "shuu"], "3年"),
            Kanji("緑", ["midori", "ryoku"], "3年"),
            Kanji("練", ["ren", "neru"], "3年"),
            Kanji("羊", ["hitsuji", "you"], "3年"),
            Kanji("美", ["bi", "utsukushii"], "3年"),
            Kanji("習", ["narau", "shuu"], "3年"),
            Kanji("者", ["mono", "sha"], "3年"),
            Kanji("育", ["soda(teru)", "soda", "iku"], "3年"),
            Kanji("苦", ["ku", "nigai"], "3年"),
            Kanji("荷", ["ni", "ka"], "3年"),
            Kanji("落", ["ochiru", "raku"], "3年"),
            Kanji("葉", ["ha", "you"], "3年"),
            Kanji("薬", ["kusuri", "yaku"], "3年"),
            Kanji("血", ["chi"], "3年"),
            Kanji("表", ["omote", "hyō", "hyou"], "3年"),
            Kanji("詩", ["shi"], "3年"),
            Kanji("調", ["shira(beru)", "chou", "shira"], "3年"),
            Kanji("談", ["dan"], "3年"),
            Kanji("豆", ["mame"], "3年"),
            Kanji("負", ["fu", "ou"], "3年"),
            Kanji("起", ["o(kiru)", "ki", "o"], "3年"),
            Kanji("路", ["ro", "ji"], "3年"),
            Kanji("身", ["mi"], "3年"),
            Kanji("転", ["korobu", "ten"], "3年"),
            Kanji("軽", ["karui", "kei"], "3年"),
            Kanji("農", ["nou"], "3年"),
            Kanji("返", ["kae(su)", "kae", "hen"], "3年"),
            Kanji("追", ["oi", "tsui"], "3年"),
            Kanji("送", ["oku(ru)", "sou", "oku"], "3年"),
            Kanji("速", ["soku", "haya"], "3年"),
            Kanji("進", ["susumu", "shin"], "3年"),
            Kanji("遊", ["asobu", "yuu"], "3年"),
            Kanji("運", ["hako(bu)", "un", "hako"], "3年"),
            Kanji("部", ["bu"], "3年"),
            Kanji("都", ["to", "miyako"], "3年"),
            Kanji("配", ["hai", "pai"], "3年"),
            Kanji("酒", ["sake", "shu"], "3年"),
            Kanji("重", ["juu", "omo(i)", "omo"], "3年"),
            Kanji("鉄", ["tetsu"], "3年"),
            Kanji("銀", ["gin"], "3年"),
            Kanji("開", ["a", "a(ku)", "kai", "hira", "hira(ku)"], "3年"),
            Kanji("院", ["in"], "3年"),
            Kanji("陽", ["yō", "you"], "3年"),
            Kanji("階", ["kai"], "3年"),
            Kanji("集", ["atsumeru", "shū", "shuu"], "3年"),
            Kanji("面", ["men", "omote"], "3年"),
            Kanji("題", ["dai", "toi"], "3年"),
            Kanji("飲", ["nomu", "in"], "3年"),
            Kanji("館", ["kan"], "3年"),
            Kanji("駅", ["eki"], "3年"),
            Kanji("鼻", ["hana", "bi"], "3年"),
        ]

        # Filtrar pelo nível selecionado
        kanjis_do_nivel = [k for k in banco_de_kanji if k.dificuldade == nivel_dificuldade]

        # Sortear kanjis aleatórios 
        self.perguntas = random.sample(kanjis_do_nivel, k=min(quantidade, len(kanjis_do_nivel)))
        random.shuffle(self.perguntas)

    def mostrar_proxima_pergunta(self):
        if self.indice_atual >= len(self.perguntas):
            return None
        pergunta = self.perguntas[self.indice_atual]
        print(f"\nKanji: {pergunta.caractere}")
        return pergunta

    def processar_resposta(self, resposta_usuario):
        pergunta = self.perguntas[self.indice_atual]
        correta = pergunta.verificar_resposta(resposta_usuario)
        self.pontuacao.registrar_resposta(correta)
        if correta:
            print("✅ Correto!")
        else:
            certa = pergunta.leituras[pergunta.resposta_certa]
            print(f"❌ Errado! Respostas corretas possíveis: {certa}")
        self.indice_atual += 1

    def quiz_terminado(self):
        return self.indice_atual >= len(self.perguntas)

    def mostrar_resultado_final(self):
        self.pontuacao.mostrar_resultado()