<<<<<<< HEAD
# Generated by Django 5.2.8 on 2026-06-29 06:34
=======
# Generated by Django 5.2.8 on 2026-04-18 15:43
>>>>>>> a2b52ac1f04430b32f7788be431403b21ff2a311

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=10, unique=True)),
                ('nivel', models.CharField(max_length=10)),
                ('leitura', models.CharField(blank=True, max_length=255, null=True)),
                ('significado', models.CharField(blank=True, max_length=255, null=True)),
                ('exemplo_jp', models.CharField(blank=True, max_length=255, null=True)),
                ('exemplo_romaji', models.CharField(blank=True, max_length=255, null=True)),
                ('exemplo_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('correta', models.CharField(blank=True, max_length=255, null=True)),
                ('alternativa1', models.CharField(blank=True, max_length=255, null=True)),
                ('alternativa2', models.CharField(blank=True, max_length=255, null=True)),
                ('alternativa3', models.CharField(blank=True, max_length=255, null=True)),
            ],
<<<<<<< HEAD
=======
            options={
                'db_table': 'app_kanji',
            },
>>>>>>> a2b52ac1f04430b32f7788be431403b21ff2a311
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('acertos', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('ordem_kanjis', models.JSONField(default=list)),
                ('ordem_alternativas', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('correta', models.BooleanField(default=False)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='app.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField()),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alternativa')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kanji')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='app.quizsession')),
            ],
        ),
    ]
