# Generated by Django 5.2.8 on 2026-06-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=10, unique=True)),
                ('leitura', models.CharField(max_length=100)),
                ('significado', models.CharField(max_length=200)),
                ('nivel', models.CharField(max_length=10)),
                ('dica', models.TextField(blank=True, default='')),
                ('exemplo_jp', models.TextField(blank=True, default='')),
                ('exemplo_romaji', models.TextField(blank=True, default='')),
                ('exemplo_pt', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('acertos', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('ordem_kanjis', models.JSONField(default=list)),
                ('ordem_alternativas', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('correta', models.BooleanField(default=False)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='app.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField()),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.alternativa')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kanji')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='app.quizsession')),
            ],
        ),
    ]
