# Generated by Django 5.2.8 on 2026-04-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kanji',
            table=None,
        ),
    ]
