# Generated by Django 5.2.8 on 2026-06-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_kanji_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='dica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
